# Este arquivo configura o analisador, que analisa estaticamente o código Dart para
# verificar erros, avisos e dicas.
#
# Os problemas identificados pelo analisador são exibidos na interface do usuário dos IDEs habilitados para Dart
# (https://dart.dev/tools#ides-and-editors). O analisador também pode ser
# invocado a partir da linha de comando executando `flutter analyze`.
#
# A linha a seguir ativa um conjunto de dicas recomendadas para aplicativos Flutter,
# pacotes e plugins projetados para incentivar boas práticas de codificação.
include: package:flutter_lints/flutter.yaml

linter:
  # As regras de dicas aplicadas a este projeto podem ser personalizadas na
  # seção abaixo para desativar regras do `package:flutter_lints/flutter.yaml`
  # incluído acima ou para habilitar regras adicionais. Uma lista de todas as dicas disponíveis
  # e sua documentação são publicadas em https://dart.dev/lints.
  #
  # Em vez de desativar uma regra de dica para todo o projeto na
  # seção abaixo, ela também pode ser suprimida para uma única linha de código
  # ou um arquivo Dart específico usando a sintaxe `// ignore: nome_da_dica` e
  # `// ignore_for_file: nome_da_dica` na linha ou no arquivo
  # produzindo a dica.
  rules:
    # avoid_print: false  # Descomente para desativar a regra `avoid_print`
    # prefer_single_quotes: true  # Descomente para ativar a regra `prefer_single_quotes`

# Informações adicionais sobre este arquivo podem ser encontradas em
# https://dart.dev/guides/language/analysis-options
