name: books
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  fluttertoast: ^8.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png

  uses-material-design: true

